[project]
name = 'Tokenized-Agriculture-Food-Traceability-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.producer-verification]
path = 'contracts/producer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-certification]
path = 'contracts/quality-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
